name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --no-root
          poetry install --with dev 

      - name: Run Ruff (Linting)
        run: |
          poetry run ruff check .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --no-root
          poetry install --with dev 
          poetry install --extras "spacy"

      - name: Run Pytest with coverage
        run: |
          poetry run pytest --cov=./ --cov-fail-under=80 --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/  # Diretório gerado pelo pytest-cov para relatórios de cobertura HTML

      - name: Display coverage in the console
        run: |
          poetry run pytest --cov-report term --cov=./  # Mostra a cobertura no terminal
